/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as AnglictinaProDospeleRouteImport } from './routes/anglictina-pro-dospele'
import { Route as AnglictinaProDetiRouteImport } from './routes/anglictina-pro-deti'
import { Route as AnglickaSkolickaRouteImport } from './routes/anglicka-skolicka'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ONasIndexRouteImport } from './routes/o-nas.index'
import { Route as AktualityIndexRouteImport } from './routes/aktuality.index'
import { Route as ONasNasTymRouteImport } from './routes/o-nas.nas-tym'
import { Route as AktualitySlugRouteImport } from './routes/aktuality.$slug'

const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const AnglictinaProDospeleRoute = AnglictinaProDospeleRouteImport.update({
  id: '/anglictina-pro-dospele',
  path: '/anglictina-pro-dospele',
  getParentRoute: () => rootRouteImport,
} as any)
const AnglictinaProDetiRoute = AnglictinaProDetiRouteImport.update({
  id: '/anglictina-pro-deti',
  path: '/anglictina-pro-deti',
  getParentRoute: () => rootRouteImport,
} as any)
const AnglickaSkolickaRoute = AnglickaSkolickaRouteImport.update({
  id: '/anglicka-skolicka',
  path: '/anglicka-skolicka',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasIndexRoute = ONasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ONasRoute,
} as any)
const AktualityIndexRoute = AktualityIndexRouteImport.update({
  id: '/aktuality/',
  path: '/aktuality/',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasNasTymRoute = ONasNasTymRouteImport.update({
  id: '/nas-tym',
  path: '/nas-tym',
  getParentRoute: () => ONasRoute,
} as any)
const AktualitySlugRoute = AktualitySlugRouteImport.update({
  id: '/aktuality/$slug',
  path: '/aktuality/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anglicka-skolicka': typeof AnglickaSkolickaRoute
  '/anglictina-pro-deti': typeof AnglictinaProDetiRoute
  '/anglictina-pro-dospele': typeof AnglictinaProDospeleRoute
  '/gdpr': typeof GdprRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRouteWithChildren
  '/aktuality/$slug': typeof AktualitySlugRoute
  '/o-nas/nas-tym': typeof ONasNasTymRoute
  '/aktuality/': typeof AktualityIndexRoute
  '/o-nas/': typeof ONasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anglicka-skolicka': typeof AnglickaSkolickaRoute
  '/anglictina-pro-deti': typeof AnglictinaProDetiRoute
  '/anglictina-pro-dospele': typeof AnglictinaProDospeleRoute
  '/gdpr': typeof GdprRoute
  '/kontakt': typeof KontaktRoute
  '/aktuality/$slug': typeof AktualitySlugRoute
  '/o-nas/nas-tym': typeof ONasNasTymRoute
  '/aktuality': typeof AktualityIndexRoute
  '/o-nas': typeof ONasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anglicka-skolicka': typeof AnglickaSkolickaRoute
  '/anglictina-pro-deti': typeof AnglictinaProDetiRoute
  '/anglictina-pro-dospele': typeof AnglictinaProDospeleRoute
  '/gdpr': typeof GdprRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRouteWithChildren
  '/aktuality/$slug': typeof AktualitySlugRoute
  '/o-nas/nas-tym': typeof ONasNasTymRoute
  '/aktuality/': typeof AktualityIndexRoute
  '/o-nas/': typeof ONasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anglicka-skolicka'
    | '/anglictina-pro-deti'
    | '/anglictina-pro-dospele'
    | '/gdpr'
    | '/kontakt'
    | '/o-nas'
    | '/aktuality/$slug'
    | '/o-nas/nas-tym'
    | '/aktuality/'
    | '/o-nas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anglicka-skolicka'
    | '/anglictina-pro-deti'
    | '/anglictina-pro-dospele'
    | '/gdpr'
    | '/kontakt'
    | '/aktuality/$slug'
    | '/o-nas/nas-tym'
    | '/aktuality'
    | '/o-nas'
  id:
    | '__root__'
    | '/'
    | '/anglicka-skolicka'
    | '/anglictina-pro-deti'
    | '/anglictina-pro-dospele'
    | '/gdpr'
    | '/kontakt'
    | '/o-nas'
    | '/aktuality/$slug'
    | '/o-nas/nas-tym'
    | '/aktuality/'
    | '/o-nas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnglickaSkolickaRoute: typeof AnglickaSkolickaRoute
  AnglictinaProDetiRoute: typeof AnglictinaProDetiRoute
  AnglictinaProDospeleRoute: typeof AnglictinaProDospeleRoute
  GdprRoute: typeof GdprRoute
  KontaktRoute: typeof KontaktRoute
  ONasRoute: typeof ONasRouteWithChildren
  AktualitySlugRoute: typeof AktualitySlugRoute
  AktualityIndexRoute: typeof AktualityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anglictina-pro-dospele': {
      id: '/anglictina-pro-dospele'
      path: '/anglictina-pro-dospele'
      fullPath: '/anglictina-pro-dospele'
      preLoaderRoute: typeof AnglictinaProDospeleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anglictina-pro-deti': {
      id: '/anglictina-pro-deti'
      path: '/anglictina-pro-deti'
      fullPath: '/anglictina-pro-deti'
      preLoaderRoute: typeof AnglictinaProDetiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anglicka-skolicka': {
      id: '/anglicka-skolicka'
      path: '/anglicka-skolicka'
      fullPath: '/anglicka-skolicka'
      preLoaderRoute: typeof AnglickaSkolickaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas/': {
      id: '/o-nas/'
      path: '/'
      fullPath: '/o-nas/'
      preLoaderRoute: typeof ONasIndexRouteImport
      parentRoute: typeof ONasRoute
    }
    '/aktuality/': {
      id: '/aktuality/'
      path: '/aktuality'
      fullPath: '/aktuality/'
      preLoaderRoute: typeof AktualityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas/nas-tym': {
      id: '/o-nas/nas-tym'
      path: '/nas-tym'
      fullPath: '/o-nas/nas-tym'
      preLoaderRoute: typeof ONasNasTymRouteImport
      parentRoute: typeof ONasRoute
    }
    '/aktuality/$slug': {
      id: '/aktuality/$slug'
      path: '/aktuality/$slug'
      fullPath: '/aktuality/$slug'
      preLoaderRoute: typeof AktualitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ONasRouteChildren {
  ONasNasTymRoute: typeof ONasNasTymRoute
  ONasIndexRoute: typeof ONasIndexRoute
}

const ONasRouteChildren: ONasRouteChildren = {
  ONasNasTymRoute: ONasNasTymRoute,
  ONasIndexRoute: ONasIndexRoute,
}

const ONasRouteWithChildren = ONasRoute._addFileChildren(ONasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnglickaSkolickaRoute: AnglickaSkolickaRoute,
  AnglictinaProDetiRoute: AnglictinaProDetiRoute,
  AnglictinaProDospeleRoute: AnglictinaProDospeleRoute,
  GdprRoute: GdprRoute,
  KontaktRoute: KontaktRoute,
  ONasRoute: ONasRouteWithChildren,
  AktualitySlugRoute: AktualitySlugRoute,
  AktualityIndexRoute: AktualityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
